version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: questionnaire-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./infrastructure/mongodb/init.js:/docker-entrypoint-initdb.d/init.js

  redis:
    image: redis:6.2-alpine
    container_name: questionnaire-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: questionnaire-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/questionnaire?authSource=admin
      REDIS_URI: redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  admin-panel:
    build: ./admin-panel
    container_name: questionnaire-admin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
  redis_data:
